---
services:
  solark_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: solark_monitor:latest
    environment:
      - SOLARK_LOG_LEVEL=${SOLARK_LOG_LEVEL}
      - SOLARK_LOG_PATH=${SOLARK_LOG_PATH}
      - SOLARK_INV_HOSTNAME=${SOLARK_INV_HOSTNAME}
      - SOLARK_DB_HOSTNAME=${SOLARK_DB_HOSTNAME}
      - SOLARK_DB_USERNAME=${SOLARK_DB_USERNAME}
      - SOLARK_DB_PASSWORD=${SOLARK_DB_PASSWORD}
      - SOLARK_DB_SCHEMA=${SOLARK_DB_SCHEMA}
      - SOLARK_DB_TABLE=${SOLARK_DB_TABLE}
    volumes:
      - /var/log/solark_monitor:/app/log:z