"""A Python list created to make a few short cuts when communicating with the Sol-Ark Inverter."""
# !/usr/bin/env python
# -*- coding: utf-8 -*-
#

register_table = [
    {
        "address": 60,
        "description": "day_active_power",
        "key": "day_active_power",
        "permission": "R",
        "range": [-32768, 32767],
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 63,
        "description": "total_active_power_low_word",
        "key": "total_active_power_low_word",
        "permission": "R",
        "range": [0, 2147483647],
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 64,
        "description": "total_active_power_high_word",
        "key": "total_active_power_high_word",
        "permission": "R",
        "range": [0, 2147483647],
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 79,
        "description": "grid_frequency",
        "key": "grid_frequency",
        "permission": "R",
        "range": [0, 9999],
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 90,
        "description": "dcdc_transformer_temp",
        "key": "dcdc_transformer_temp",
        "permission": "R",
        "range": [0, 3000],
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 91,
        "description": "igbt_heat_sink_temp",
        "key": "igbt_heat_sink_temp",
        "permission": "R",
        "range": [0, 3000],
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 103,
        "description": "fault_info_word_1",
        "key": "fault_info_word_1",
        "permission": "R",
        "range": [0, 65535],
        "unit": "str",
        "pull": True,
    },
    {
        "address": 104,
        "description": "fault_info_word_2",
        "key": "fault_info_word_2",
        "permission": "R",
        "range": [0, 65535],
        "unit": "str",
        "pull": True,
    },
    {
        "address": 105,
        "description": "fault_info_word_3",
        "key": "fault_info_word_3",
        "permission": "R",
        "range": [0, 65535],
        "unit": "str",
        "pull": True,
    },
    {
        "address": 106,
        "description": "fault_info_word_4",
        "key": "fault_info_word_4",
        "permission": "R",
        "range": [0, 65535],
        "unit": "str",
        "pull": True,
    },
    {
        "address": 107,
        "description": "corrected_batt_capacity",
        "key": "corrected_batt_capacity",
        "permission": "R",
        "range": [0, 100],
        "unit": "str",
        "pull": True,
    },
    {
        "address": 108,
        "description": "daily_pv_power",
        "key": "daily_pv_power",
        "permission": "R",
        "range": [0, 65535],
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 109,
        "description": "dc_voltage_1",
        "key": "dc_voltage_1",
        "permission": "R",
        "range": [0, 65535],
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 110,
        "description": "dc_current_1",
        "key": "dc_current_1",
        "permission": "R",
        "range": [0, 65535],
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 111,
        "description": "dc_voltage_2",
        "key": "dc_voltage_2",
        "permission": "R",
        "range": [0, 65535],
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 112,
        "description": "dc_current_2",
        "key": "dc_current_2",
        "permission": "R",
        "range": [0, 65535],
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 150,
        "description": "grid_side_voltage_l1n",
        "key": "grid_side_voltage_l1n",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 151,
        "description": "grid_side_voltage_l2n",
        "key": "grid_side_voltage_l2n",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 152,
        "description": "grid_side_voltage_l1l2",
        "key": "grid_side_voltage_l1l2",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 153,
        "description": "voltage_middle_side_relay_l1l2",
        "key": "voltage_middle_side_relay_l1l2",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 154,
        "description": "inverter_output_voltage_l1n",
        "key": "inverter_output_voltage_l1n",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 155,
        "description": "inverter_output_voltage_l2n",
        "key": "inverter_output_voltage_l2n",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 156,
        "description": "inverter_output_voltage_l1l2",
        "key": "inverter_output_voltage_l1l2",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 157,
        "description": "load_voltage_l1",
        "key": "load_voltage_l1",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 158,
        "description": "load_voltage_l2",
        "key": "load_voltage_l2",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 160,
        "description": "grid_side_current_l1",
        "key": "grid_side_current_l1",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 161,
        "description": "grid_side_current_l2",
        "key": "grid_side_current_l2",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 162,
        "description": "grid_external_limiter_current_l1",
        "key": "grid_external_limiter_current_l1",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 163,
        "description": "grid_external_limiter_current_l2",
        "key": "grid_external_limiter_current_l2",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 164,
        "description": "inverter_output_current_l1",
        "key": "inverter_output_current_l1",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 165,
        "description": "inverter_output_current_l2",
        "key": "inverter_output_current_l2",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 166,
        "description": "gen_ac_coupled_power_input",
        "key": "gen_ac_coupled_power_input",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 167,
        "description": "grid_side_l1_power",
        "key": "grid_side_l1_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 168,
        "description": "grid_side_l2_power",
        "key": "grid_side_l2_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 169,
        "description": "total_power_grid_side_l1l2",
        "key": "total_power_grid_side_l1l2",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 170,
        "description": "grid_external_limiter1_power",
        "key": "grid_external_limiter1_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 171,
        "description": "grid_external_limiter2_power",
        "key": "grid_external_limiter2_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 172,
        "description": "grid_external_total_power",
        "key": "grid_external_total_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 173,
        "description": "inverter_outputs_l1_power",
        "key": "inverter_outputs_l1_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 174,
        "description": "inverter_outputs_l2_power",
        "key": "inverter_outputs_l2_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 175,
        "description": "inverter_output_total_power",
        "key": "inverter_output_total_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 176,
        "description": "load_side_l1_power",
        "key": "load_side_l1_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 177,
        "description": "load_side_l2_power",
        "key": "load_side_l2_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 178,
        "description": "load_side_total_power",
        "key": "load_side_total_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 179,
        "description": "load_current_l1",
        "key": "load_current_l1",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 180,
        "description": "load_current_l2",
        "key": "load_current_l2",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 181,
        "description": "gen_port_voltage_l1l2",
        "key": "gen_port_voltage_l1l2",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 182,
        "description": "battery_temp",
        "key": "battery_temp",
        "permission": "R",
        "range": [0, 3000],
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 183,
        "description": "battery_voltage",
        "key": "battery_voltage",
        "permission": "R",
        "range": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 184,
        "description": "battery_capacity_soc",
        "key": "battery_capacity_soc",
        "permission": "R",
        "range": [0, 100],
        "unit": "percent",
        "pull": True,
    },
    {
        "address": 186,
        "description": "pv1_input_power",
        "key": "pv1_input_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 187,
        "description": "pv2_input_power",
        "key": "pv2_input_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 190,
        "description": "battery_output_power",
        "key": "battery_output_power",
        "permission": "R",
        "range": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 191,
        "description": "battery_output_current",
        "key": "battery_output_current",
        "permission": "R",
        "range": None,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 192,
        "description": "load_frequency",
        "key": "load_frequency",
        "permission": "R",
        "range": None,
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 193,
        "description": "inverter_output_frequency",
        "key": "inverter_output_frequency",
        "permission": "R",
        "range": None,
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 194,
        "description": "grid_side_relay_status",
        "key": "grid_side_relay_status",
        "permission": "R",
        "range": None,
        "unit": "integer",
        "pull": True,
    },
    {
        "address": 195,
        "description": "generator_side_relay_status",
        "key": "generator_side_relay_status",
        "permission": "R",
        "range": None,
        "unit": "integer",
        "pull": True,
    },
    {
        "address": 196,
        "description": "generator_relay_frequency",
        "key": "generator_relay_frequency",
        "permission": "R",
        "range": None,
        "unit": "hz",
        "pull": True,
    },
]
