{
 "title": "Sol-Ark Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total PV Input Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$PV1 + $PV2", "type": "math" }
   ]
  },
  {
   "title": "PV1 Input Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pv1_input_power\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Load Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  load_side_total_power\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Load L1 Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  load_side_l1_power\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "PV2 Input Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pv2_input_power\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Load L2 Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  load_side_l2_power\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Battery State-of-Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_capacity_soc\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_voltage\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Grid Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_voltage\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Energy Generation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expression": "$PV1 + $PV2", "type": "math" },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_output_power AS \"Battery\"\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  load_side_total_power AS \"Load\"\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  total_power_grid_side_l1l2 AS \"Grid\"\nFROM solarkmon\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}