CREATE DATABASE /*!32312 IF NOT EXISTS*/ `solarkmon` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

USE `solarkmon`;

DROP TABLE IF EXISTS `solarkmon`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `solarkmon` (
  `data_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `datetime` datetime DEFAULT NULL,
  `timestamp` int(10) DEFAULT NULL,
  `day_active_power` decimal(3,1) DEFAULT NULL,
  `total_active_power_low_word` decimal(10,1) unsigned DEFAULT NULL,
  `total_active_power_high_word` decimal(10,1) unsigned DEFAULT NULL,
  `grid_frequency` decimal(3,1) unsigned DEFAULT NULL,
  `dcdc_transformer_temp` decimal(4,1) unsigned DEFAULT NULL,
  `igbt_heat_sink_temp` decimal(4,1) unsigned DEFAULT NULL,
  `fault_info_word_1` smallint(5) unsigned DEFAULT NULL,
  `fault_info_word_2` smallint(5) unsigned DEFAULT NULL,
  `fault_info_word_3` smallint(5) unsigned DEFAULT NULL,
  `fault_info_word_4` smallint(5) unsigned DEFAULT NULL,
  `corrected_batt_capacity` smallint(5) unsigned DEFAULT NULL,
  `daily_pv_power` decimal(3,1) unsigned DEFAULT NULL,
  `dc_voltage_1` decimal(4,1) unsigned DEFAULT NULL,
  `dc_current_1` decimal(4,1) unsigned DEFAULT NULL,
  `dc_voltage_2` decimal(4,1) unsigned DEFAULT NULL,
  `dc_current_2` decimal(4,1) unsigned DEFAULT NULL,
  `grid_side_voltage_l1n` decimal(4,1) unsigned DEFAULT NULL,
  `grid_side_voltage_l2n` decimal(4,1) unsigned DEFAULT NULL,
  `grid_side_voltage_l1l2` decimal(4,1) unsigned DEFAULT NULL,
  `voltage_middle_side_relay_l1l2` decimal(4,1) unsigned DEFAULT NULL,
  `inverter_output_voltage_l1n` decimal(4,1) unsigned DEFAULT NULL,
  `inverter_output_voltage_l2n` decimal(4,1) unsigned DEFAULT NULL,
  `inverter_output_voltage_l1l2` decimal(4,1) unsigned DEFAULT NULL,
  `load_voltage_l1` decimal(4,1) unsigned DEFAULT NULL,
  `load_voltage_l2` decimal(4,1) unsigned DEFAULT NULL,
  `grid_side_current_l1` decimal(4,2) DEFAULT NULL,
  `grid_side_current_l2` decimal(4,2) DEFAULT NULL,
  `grid_external_limiter_current_l1` decimal(4,2) DEFAULT NULL,
  `grid_external_limiter_current_l2` decimal(4,2) DEFAULT NULL,
  `inverter_output_current_l1` decimal(4,2) DEFAULT NULL,
  `inverter_output_current_l2` decimal(4,2) DEFAULT NULL,
  `gen_ac_coupled_power_input` smallint(6) DEFAULT NULL,
  `grid_side_l1_power` smallint(6) DEFAULT NULL,
  `grid_side_l2_power` smallint(6) DEFAULT NULL,
  `total_power_grid_side_l1l2` smallint(6) DEFAULT NULL,
  `grid_external_limiter1_power` smallint(6) DEFAULT NULL,
  `grid_external_limiter2_power` smallint(6) DEFAULT NULL,
  `grid_external_total_power` smallint(6) DEFAULT NULL,
  `inverter_outputs_l1_power` smallint(6) DEFAULT NULL,
  `inverter_outputs_l2_power` smallint(6) DEFAULT NULL,
  `inverter_output_total_power` smallint(6) DEFAULT NULL,
  `load_side_l1_power` smallint(6) DEFAULT NULL,
  `load_side_l2_power` smallint(6) DEFAULT NULL,
  `load_side_total_power` smallint(6) DEFAULT NULL,
  `load_current_l1` decimal(4,2) DEFAULT NULL,
  `load_current_l2` decimal(4,2) DEFAULT NULL,
  `gen_port_voltage_l1l2` smallint(6) DEFAULT NULL,
  `battery_temp` decimal(4,1) unsigned DEFAULT NULL,
  `battery_voltage` decimal(3,1) unsigned DEFAULT NULL,
  `battery_capacity_soc` tinyint(3) unsigned DEFAULT NULL,
  `pv1_input_power` smallint(5) unsigned DEFAULT NULL,
  `pv2_input_power` smallint(5) unsigned DEFAULT NULL,
  `battery_output_power` smallint(6) DEFAULT NULL,
  `battery_output_current` decimal(4,2) DEFAULT NULL,
  `load_frequency` decimal(4,2) unsigned DEFAULT NULL,
  `inverter_output_frequency` decimal(3,1) unsigned DEFAULT NULL,
  `grid_side_relay_status` tinyint(3) unsigned DEFAULT NULL,
  `generator_side_relay_status` tinyint(3) unsigned DEFAULT NULL,
  `generator_relay_frequency` decimal(2,1) unsigned DEFAULT NULL,
  PRIMARY KEY (`data_id`),
  UNIQUE KEY `idnew_table_UNIQUE` (`data_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;