"""A Python list with the Sol-Ark Memory Registers."""

# !/usr/bin/env python
# -*- coding: utf-8 -*-
#

register_table = [
    {
        "address": 60,
        "description": "Day Active Power Wh",
        "key": "day_active_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": 10,
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 63,
        "description": "Total Active Power (Wh) low word",
        "key": "total_active_power_low_word",
        "permission": "R",
        "signed": False,
        "bits": 32,
        "range": [0, 2147483647],
        "multiplier": 10,
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 64,
        "description": "Total Active Power (Wh) high word",
        "key": "total_active_power_high_word",
        "permission": "R",
        "signed": False,
        "bits": 32,
        "range": [0, 2147483647],
        "multiplier": 10,
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 79,
        "description": "Grid Frequency",
        "key": "grid_frequency",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 9999],
        "multiplier": 100,
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 90,
        "description": "DC/DC Transformer temperature",
        "key": "dcdc_transformer_temp",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 3000],
        "multiplier": 10,
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 91,
        "description": "IGBT Heat Sink temperature",
        "key": "igbt_heat_sink_temp",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 3000],
        "multiplier": 10,
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 103,
        "description": "Fault information word 1",
        "key": "fault_info_word_1",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": None,
        "unit": "str",
        "pull": True,
    },
    {
        "address": 104,
        "description": "Fault information word 2",
        "key": "fault_info_word_2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": None,
        "unit": "str",
        "pull": True,
    },
    {
        "address": 105,
        "description": "Fault information word 3",
        "key": "fault_info_word_3",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": None,
        "unit": "str",
        "pull": True,
    },
    {
        "address": 106,
        "description": "Fault information word 4",
        "key": "fault_info_word_4",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": None,
        "unit": "str",
        "pull": True,
    },
    {
        "address": 107,
        "description": "Corrected Batt Capacity",
        "key": "corrected_batt_capacity",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 1000],
        "multiplier": None,
        "unit": "str",
        "pull": True,
    },
    {
        "address": 108,
        "description": "Daily PV Power (Wh)",
        "key": "daily_pv_power",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": 10,
        "unit": "kwh",
        "pull": True,
    },
    {
        "address": 109,
        "description": "DC voltage 1",
        "key": "dc_voltage_1",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 110,
        "description": "DC current 1",
        "key": "dc_current_1",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": 10,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 111,
        "description": "DC voltage 2",
        "key": "dc_voltage_2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 112,
        "description": "DC current 2",
        "key": "dc_current_2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 65535],
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 150,
        "description": "Grid side voltage L1-N",
        "key": "grid_side_voltage_l1n",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 151,
        "description": "Grid side voltage L2-N",
        "key": "grid_side_voltage_l2n",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 152,
        "description": "Grid side voltage L1-L2",
        "key": "grid_side_voltage_l1l2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 153,
        "description": "Voltage at middle side of relay L1-L2",
        "key": "voltage_middle_side_relay_l1l2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 154,
        "description": "Inverter output voltage L1-N",
        "key": "inverter_output_voltage_l1n",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 155,
        "description": "Inverter output voltage L2-N",
        "key": "inverter_output_voltage_l2n",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 156,
        "description": "Inverter output voltage L1-L2",
        "key": "inverter_output_voltage_l1l2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 157,
        "description": "Load voltage L1",
        "key": "load_voltage_l1",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 158,
        "description": "Load voltage L2",
        "key": "load_voltage_l2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 10,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 160,
        "description": "Grid side current L1",
        "key": "grid_side_current_l1",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 161,
        "description": "Grid side current L2",
        "key": "grid_side_current_l2",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 162,
        "description": "Grid external Limiter current L1",
        "key": "grid_external_limiter_current_l1",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 163,
        "description": "Grid external Limiter current L2",
        "key": "grid_external_limiter_current_l2",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 164,
        "description": "Inverter output current L1",
        "key": "inverter_output_current_l1",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 165,
        "description": "Inverter output current L2",
        "key": "inverter_output_current_l2",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 166,
        "description": "Gen or AC Coupled power input",
        "key": "gen_ac_coupled_power_input",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 167,
        "description": "Grid side L1 power",
        "key": "grid_side_l1_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-12000, 12000],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 168,
        "description": "Grid side L2 power",
        "key": "grid_side_l2_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-12000, 12000],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 169,
        "description": "Total power of grid side L1-L2",
        "key": "total_power_grid_side_l1l2",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 170,
        "description": "Grid external Limiter1 power (CT1)",
        "key": "grid_external_limiter1_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 171,
        "description": "Grid external Limiter2 power (CT2)",
        "key": "grid_external_limiter2_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 172,
        "description": "Grid external Total Power",
        "key": "grid_external_total_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 173,
        "description": "Inverter outputs L1 power",
        "key": "inverter_outputs_l1_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 174,
        "description": "Inverter outputs L2 power",
        "key": "inverter_outputs_l2_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 175,
        "description": "Inverter output Total power",
        "key": "inverter_output_total_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 176,
        "description": "Load side L1 power",
        "key": "load_side_l1_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 177,
        "description": "Load side L2 power",
        "key": "load_side_l2_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 178,
        "description": "Load side Total power",
        "key": "load_side_total_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 179,
        "description": "Load current L1",
        "key": "load_current_l1",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 180,
        "description": "Load current L2",
        "key": "load_current_l2",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 181,
        "description": "Gen Port Voltage L1-L2",
        "key": "gen_port_voltage_l1l2",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 182,
        "description": "Battery temperature",
        "key": "battery_temp",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 3000],
        "multiplier": 10,
        "unit": "celsius",
        "pull": True,
    },
    {
        "address": 183,
        "description": "Battery voltage",
        "key": "battery_voltage",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "volt",
        "pull": True,
    },
    {
        "address": 184,
        "description": "Battery capacity SOC",
        "key": "battery_capacity_soc",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": [0, 100],
        "multiplier": None,
        "unit": "percent",
        "pull": True,
    },
    {
        "address": 186,
        "description": "PV1 input power",
        "key": "pv1_input_power",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 187,
        "description": "PV2 input power",
        "key": "pv2_input_power",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 190,
        "description": "Battery output power",
        "key": "battery_output_power",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": None,
        "unit": "watt",
        "pull": True,
    },
    {
        "address": 191,
        "description": "Battery output current",
        "key": "battery_output_current",
        "permission": "R",
        "signed": True,
        "bits": 16,
        "range": [-32768, 32767],
        "multiplier": 100,
        "unit": "amp",
        "pull": True,
    },
    {
        "address": 192,
        "description": "Load frequency",
        "key": "load_frequency",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 193,
        "description": "Inverter output frequency",
        "key": "inverter_output_frequency",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "hz",
        "pull": True,
    },
    {
        "address": 194,
        "description": "Grid side relay status",
        "key": "grid_side_relay_status",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "integer",
        "pull": True,
    },
    {
        "address": 195,
        "description": "Generator side relay status",
        "key": "generator_side_relay_status",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": None,
        "unit": "integer",
        "pull": True,
    },
    {
        "address": 196,
        "description": "Generator relay Frequency",
        "key": "generator_relay_frequency",
        "permission": "R",
        "signed": False,
        "bits": 16,
        "range": None,
        "multiplier": 100,
        "unit": "hz",
        "pull": True,
    },
]
